{
	"version": 1657732622,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/moomiyayi-sheet0.png",
		"images/quest_deadman-sheet0.png",
		"images/doors-sheet0.png",
		"images/platform-sheet0.png",
		"images/switch_off-sheet0.png",
		"images/switch_on-sheet0.png",
		"images/exitsign-sheet0.png",
		"media/gun7.ogg",
		"media/goldenegg.ogg",
		"media/s flower breaking scoreitem.ogg",
		"media/s fruit breaking scoreitem.ogg",
		"media/piano-d.ogg",
		"media/s bird 05 flying.ogg",
		"media/scrapescrapescrape.ogg",
		"media/discovery4.ogg",
		"media/wogthemeloop.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}