{
	"version": 1658010513,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/ghost-sheet0.png",
		"images/ghost-sheet1.png",
		"images/fruit-sheet0.png",
		"images/fruit-sheet1.png",
		"images/pacman-sheet0.png",
		"images/dot-sheet0.png",
		"images/powerpill-sheet0.png",
		"images/powerpill-sheet1.png",
		"images/frameh.png",
		"images/framev.png",
		"images/den-sheet0.png",
		"images/nodot-sheet0.png",
		"images/door.png",
		"images/controller-sheet0.png",
		"images/statictext.png",
		"images/pacmanlives-sheet0.png",
		"images/blanker-sheet0.png",
		"images/chap-sheet0.png",
		"images/rast-sheet0.png",
		"images/bala-sheet0.png",
		"images/payin-sheet0.png",
		"images/tchap-sheet0.png",
		"images/sprite-sheet0.png",
		"images/back-sheet0.png",
		"images/backgroundsplash-sheet0.png",
		"images/touchsplash-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/mahdismltext-sheet0.png",
		"images/انانان-sheet0.png",
		"images/khkh-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/kksback-sheet0.png",
		"images/kksphone-sheet0.png",
		"images/kksbutton-sheet0.png",
		"images/inffooo-sheet0.png",
		"media/death.m4a",
		"media/chasing sound.m4a",
		"media/chasing sound.ogg",
		"media/death.ogg",
		"media/eat dot.m4a",
		"media/eat ghost.m4a",
		"media/extra life.m4a",
		"media/ghost returning.m4a",
		"media/ghost returning.ogg",
		"media/high siren.m4a",
		"media/high siren.ogg",
		"media/intermission.m4a",
		"media/intermission.ogg",
		"media/intro.m4a",
		"media/intro.ogg",
		"media/eat dot.ogg",
		"media/eat ghost.ogg",
		"media/extra life.ogg",
		"media/low siren.m4a",
		"media/low siren.ogg",
		"media/eat fruit.m4a",
		"media/eat fruit.ogg",
		"icon-256.png",
		"loading-logo.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"pathfind.js"
	]
}